### ISSUE TITLE
Add Docker Hub descriptions

### ISSUE THREAD

**Issue by virtualroot** [virtualroot/docker-hardened#1]
Add Docker Hub repository descriptions

- https://hub.docker.com/r/virtualroot/hardened-alpine
- https://hub.docker.com/r/virtualroot/hardened-debian
- https://hub.docker.com/r/virtualroot/hardened-ubuntu

Example:
```yml
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: peterevans/dockerhub-description
```
